### ISSUE TITLE
Glass pane tops/bottoms are not CTM'd properly

### ISSUE THREAD

**Issue by Leo40Git** [Nuclearfarts/connected-block-textures#1]
![2020-05-28_14 05 05](https://user-images.githubusercontent.com/7997354/83134112-8ad28580-a0ec-11ea-9528-4c9919c34f2c.png)
This can also be seen in the demonstration screenshot on CF.

This might be a resource pack issue, I'll grab OptiFine's CTM stuff and try it.

**Comment by Leo40Git** [comment]
Okay, so, two things learned:
1. Straight ports from OF to CBT are not possible (due to OF's files missing some hints OF infers)
2. This is seemingly a bug with the code itself, not just the included resource pack

**Comment by TwilightFlower** [comment]
This is a special-cased modification to the model of the glass panes in Optifine. This is possible to fix in a resource pack by setting the cull face of the top and bottom quads in the glass pane model. I do not plan to implement this special case in CBT because it goes beyond the scope of supporting Optifine CTM into making visual changes to the game, and, well, you can do it with a resource pack.

As for the stuff you just mentioned about straight ports, please make another issue with clarification. I'd be happy to fix any problems of that sort.

**Comment by Leo40Git** [comment]
I'm pretty sure straight ports don't work for glass only, because of your additional properties for it. I didn't check other blocks with OF's resources.

**Comment by Leo40Git** [comment]
For anyone who wants to fix the culling: [CBT Glass Pane Fix.zip](https://github.com/Nuclearfarts/connected-block-textures/files/4702258/CBT.Glass.Pane.Fix.zip)
This fix modifies the template models, so it'll work with all vanilla glass panes, and should work with most modded panes.
**edit:** This resource pack is licensed as MIT, and is free to use by anyone. It can even be included in other mods, modpacks and resource packs (but give credit, at least).

**Comment by TwilightFlower** [comment]
Are you saying there's an issue overriding the default glass pane configs? If so, that's a problem, considering they... are supposed to override in resource pack order.

**Comment by Leo40Git** [comment]
I don't think there's an issue. OptiFine's resources just don't work with the mod. I haven't tried an actual resource pack yet.

**Comment by calloatti** [comment]
@Leo40Git can these files you posted be incorporated into a modpack?

**Comment by Leo40Git** [comment]
@calloatti Just include the resource pack and tell people to not disable it.
You could also shove it in a mod if you really wanted.

**Comment by calloatti** [comment]
I was asking for your permission, assuming you made them. Thanks.

**Comment by Leo40Git** [comment]
@calloatti oh. yeah i made this pack, i give you permission and stuff

**Comment by calloatti** [comment]
Thank you!

**Comment by VencislavIvanov** [comment]
Hey, I downloaded the resource pack you put up in the comments but minecraft doesn't seem to recognize it as a resource pack so I can't select it from the menu. Do you know how I can fix it?

**Comment by ghost** [comment]
I had the same issue, but I do not now. What fixed it for me was unarchiving it with my unarchiver program, dragging it into the resource pack menu, and clicking "Yes". Then it appeared, and I added it. Hope it helps!

**Comment by VencislavIvanov** [comment]
> I had the same issue, but I do not now. What fixed it for me was unarchiving it with my unarchiver program, dragging it into the resource pack menu, and clicking "Yes". Then it appeared, and I added it. Hope it helps!

Thank you for the answer. It worked just as you said but even with the loaded resource pack, the block textures remain the same ( they don't connect and it looks just like in vanilla minecraft )

**Comment by MulverineX** [comment]
[CBT Glass Pane Fix.zip](https://github.com/Nuclearfarts/connected-block-textures/files/5081452/CBT.Glass.Pane.Fix.zip)
Here. In the root so you don't have to do that

**Comment by JimStoneCraft** [comment]
If you add the cullface to the files listed:-

template_glass_pane_post.json
template_glass_pane_side.json
template_glass_pane_side_alt.json

It fixes the panes but breaks the pane post on top of panes.

This is one of the reasons that the vanilla game doesn't have cullface on the glass panes, OptiFine obviously has something extra to just remove the internal faces on the panes, so this cannot be fully fixed with a resource pack.

Without Cullface Bottom
![01 Without Cullface Bottom](https://user-images.githubusercontent.com/42512910/90645386-c84b3880-e22d-11ea-924f-608c0a5ef20d.png)
Without Cullface Top
![02 Without Cullface Top](https://user-images.githubusercontent.com/42512910/90645387-c8e3cf00-e22d-11ea-81aa-71946ae2cf85.png)
With Cullface Bottom
![03 With Cullface Bottom](https://user-images.githubusercontent.com/42512910/90645388-c97c6580-e22d-11ea-8dff-8a7113656479.png)
With Cullface Top
![04 With Cullface Top](https://user-images.githubusercontent.com/42512910/90645390-c97c6580-e22d-11ea-92f4-fa330f34c15b.png)
